name: "switchX"
description: >
  Switch between two files.
branding:
  icon: "file"
  color: "blue"
inputs:
  arguments:
    description: "The arguments you would pass to the switchX tool"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.arguments }}
